import { Metadata } from 'next';
import Link from 'next/link';
import { ExternalLink } from 'lucide-react';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: 'Terms of Services',
};

export default function Page() {
    return (
        <div className="min-h-screen bg-background">
            <div className="relative">
                <div className="relative pt-24 pb-12 px-4">
                    <div className="container max-w-3xl mx-auto space-y-8">
                        <div className="text-center">
                            <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
                            <p className="text-neutral-600 dark:text-neutral-400 mt-3">
                                Last updated:{' '}
                                {new Date().toLocaleDateString('en-US', {
                                    month: 'long',
                                    day: 'numeric',
                                    year: 'numeric',
                                })}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Main Content */}
            <div className="py-12 px-4">
                <div className="container max-w-3xl mx-auto prose dark:prose-invert prose-neutral prose-headings:font-syne prose-p:text-neutral-600 dark:prose-p:text-neutral-400 prose-a:text-neutral-900 dark:prose-a:text-neutral-200 prose-a:no-underline hover:prose-a:text-black dark:hover:prose-a:text-white prose-headings:tracking-tight">
                    <p className="text-lg">
                        Welcome to Retriv. These Terms of Service Terms govern your access to and use of Retriv&apos;s
                        website, tools, and services. By using Retriv, you agree to be bound by these Terms. If you do
                        not agree, please refrain from using the service.
                    </p>

                    <h2>1. Acceptance of Terms</h2>
                    <p>
                        By accessing or using Retriv, you confirm that you have read, understood, and agree to these
                        Terms. We may update these Terms at any time. Continued use of the service after updates means
                        you accept the revised Terms.
                    </p>

                    <h2>2. About Retriv</h2>
                    <p>
                        Retriv is an AI-powered platform that helps businesses and developers embed intelligent chat
                        assistants trained on their documentation. Our service indexes website or uploaded content,
                        enabling AI agents to provide context-aware responses to end users.
                    </p>
                    <p>
                        The platform may use services such as OpenAI, Anthropic, or other LLM providers for processing
                        and generating responses.
                    </p>

                    <h2>3. User Responsibilities</h2>
                    <p>By using Retriv, you agree to:</p>
                    <ul>
                        <li>Use the service in accordance with applicable laws and regulations</li>
                        <li>Not upload, generate, or transmit unlawful or harmful content</li>
                        <li>
                            Not interfere with, disrupt, or attempt to gain unauthorized access to the service or its
                            infrastructure
                        </li>
                        <li>Respect intellectual property rights of others</li>
                        <li>Not attempt to scrape, reverse engineer, or misuse the platform in any automated way</li>
                    </ul>

                    <h2>4. AI-Generated Responses</h2>
                    <p>
                        Retriv uses large language models to generate responses. While we strive for accuracy, we do not
                        guarantee that answers will be correct, complete, or suitable for specific use cases.
                    </p>
                    <ul>
                        <li>You are solely responsible for how you use the information generated by Retriv</li>
                        <li>Retriv is not liable for decisions made based on AI-generated outputs</li>
                        <li>Retriv should not be relied on for legal, medical, or critical business advice</li>
                    </ul>

                    <h2>5. Ownership and Intellectual Property</h2>
                    <p>
                        All content, branding, software, and features provided by Retriv are owned by us or our
                        licensors. You may not reproduce, modify, distribute, or reverse engineer any part of our
                        service without explicit permission.
                    </p>

                    <h2>6. Third-Party Services</h2>
                    <p>Retriv relies on third-party services for various functionalities, including:</p>
                    <ul>
                        <li>Cloud hosting (e.g., Vercel or similar)</li>
                        <li>LLM APIs (e.g., OpenAI, Anthropic, xAI)</li>
                        <li>Embeddings and vector storage (e.g., Qdrant, Redis)</li>
                    </ul>
                    <p>
                        These third parties have their own terms and privacy practices. Your data may be shared with
                        them only as necessary to operate the service.
                    </p>

                    <h2>7. Privacy</h2>
                    <p>
                        Your use of Retriv is subject to our{' '}
                        <Link href="/privacy-policy" className="underline">
                            Privacy Policy
                        </Link>
                        , which explains how we collect and handle your data.
                    </p>

                    <h2>8. Limitation of Liability</h2>
                    <p>
                        To the fullest extent permitted by law, Retriv shall not be liable for any indirect, incidental,
                        or consequential damages resulting from your use of the service.
                    </p>

                    <h2>9. Disclaimer</h2>
                    <p>
                        Retriv is provided as is without warranties of any kind. We disclaim all implied warranties,
                        including merchantability, fitness for a particular purpose, and non-infringement.
                    </p>

                    <h2>10. Suspension & Termination</h2>
                    <p>
                        We may suspend or terminate your access to Retriv at any time if we believe you have violated
                        these Terms or if your use harms the platform or its users.
                    </p>

                    <h2>11. Governing Law</h2>
                    <p>
                        These Terms shall be governed by the laws of India, without regard to conflict of law
                        principles.
                    </p>

                    <h2>12. Contact</h2>
                    <p>If you have any questions or concerns about these Terms, please reach out to:</p>
                    <p>
                        <a href="mailto:support@retriv.xyz" className="flex items-center gap-1">
                            priyanshu@retriv.xyz <ExternalLink className="h-4 w-4" />
                        </a>
                    </p>

                    <div className="my-8 border-t border-neutral-200 dark:border-neutral-800 pt-8">
                        <p className="text-sm text-neutral-500 dark:text-neutral-400">
                            By using Retriv, you agree to these Terms of Service and our{' '}
                            <Link href="/legal/privacy-policy" className="underline">
                                Privacy Policy
                            </Link>
                            .
                        </p>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
}
